version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: clazydbm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
  postgres:
    image: postgres:15
    container_name: clazydbm-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
